# PostgreSQL. Versions 9.1 and up are supported.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: pguser
  password: cals101
  database: cals-mock-api_dev

aws_dev:
  <<: *default
  host: devdb1.cs-cals.com
  username: postgres
  password:
  database: cals-mock-api_aws_dev

test:
  <<: *default
  username: pguser
  password: cals101
  database: cals-mock-api_test

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: cals-mock-api_production
  username: cals101
  password: <%= ENV['cals-mock-api_DATABASE_PASSWORD'] %>
